version: '3.2'

services:
  dynamodb:
    image: cnadiminti/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - ./.data/dynamodb:/dynamodb_local_db

  init-dynamo:
    image: garland/aws-cli-docker
    command: aws dynamodb create-table --table-name symeo-api-configurations-test --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb:8000
    links:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
    depends_on:
      - dynamodb
