aws:
  secretAccessKey:
    type: string
    optional: true
  accessKeyId:
    type: string
    optional: true
  region:
    type: string
database:
  dynamodbUrl:
    type: string
    optional: true
  configuration:
    tableName:
      type: string
auth0:
  audience:
    type: string
  issuer:
    type: string
cors:
  origin:
    type: string
    optional: true