aws:
  secretAccessKey:
    type: string
    optional: true
  accessKeyId:
    type: string
    optional: true
  region:
    type: string
database:
  dynamodbUrl:
    type: string
    optional: true
  configuration:
    tableName:
      type: string
  apiKey:
    tableName:
      type: string
auth0:
  clientId:
    type: string
  clientSecret:
    type: string
    secret: true
  audience:
    type: string
  issuer:
    type: string
  domain:
    type: string
cors:
  origin:
    type: string
    optional: true
vcsProvider:
  paginationLength:
    type: integer
datadog:
  apm:
    active:
      type: boolean
      optional: true