export enum SymeoExceptionCode {
  CONFIGURATION_NOT_FOUND = 'CONFIGURATION_NOT_FOUND',
  REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
  WRONG_REPOSITORY_DETAILS = 'WRONG_REPOSITORY_DETAILS',
  WRONG_CONFIG_FILE_DETAILS = 'WRONG_CONFIG_FILE_DETAILS',
}
