export enum SymeoExceptionCode {
  CONFIGURATION_NOT_FOUND = 'CONFIGURATION_NOT_FOUND',
  REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
  ENVIRONMENT_NOT_FOUND = 'ENVIRONMENT_NOT_FOUND',
  API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
  CONFIGURATION_CONTRACT_NOT_FOUND = 'CONFIGURATION_CONTRACT_NOT_FOUND',
  ENVIRONMENT_PERMISSION_NOT_FOUND = 'UPDATE_ADMINISTRATOR_PERMISSION',
  UPDATE_ADMINISTRATOR_PERMISSION = 'UPDATE_ADMINISTRATOR_PERMISSION',
  RESOURCE_ACCESS_DENIED = 'RESOURCE_ACCESS_DENIED',
}
