Description: Symeo API - ECS Clusters

Parameters:
  ClusterName:
    Type: String
    Default: symeo-api-cluster
  Env:
    Type: String
    Default: staging

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ClusterName}-${Env}

Outputs:
  ECSCluster:
    Value: !Ref Cluster
