Description: Symeo API - ECR Repositories

Parameters:
  SymeoApiRepositoryName:
    Type: String
    Default: symeo/api
  Env:
    Type: String
    Default: staging

Resources:
  SymeoApiRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub ${SymeoApiRepositoryName}-${Env}

Outputs:
  SymeoApiRepository:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${SymeoApiRepositoryName}-${Env}
  SymeoApiRepositoryName:
    Value: !Sub ${SymeoApiRepositoryName}-${Env}
