version: 2
jobs:
  install:
    working_directory: ~/symeo-api
    docker:
    - image: circleci/node:10.12.0
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "~/symeo-api/yarn.lock" }}
    - run:
        name: Install dependencies
        command: yarn install
    - checkout # Checking out code in case of a yarn version mismatch modifies the yarn.lock
    - save_cache:
        key: dependency-cache-{{ checksum "~/symeo-api/yarn.lock" }}
        paths:
        - node_modules
  test:
    working_directory: ~/symeo-api
    machine: true
    docker:
     - image: cimg/node:18.12.1
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "~/symeo-api/yarn.lock" }}
    - setup_remote_docker
    - run:
        name: Start database
        command: docker-compose up -d
    - run:
        name: Test
        command: yarn test
    - store_artifacts:
        path: ~/symeo-api/coverage
  lint:
    working_directory: ~/symeo-api
    docker:
    - image: circleci/node:10.12.0
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "~/symeo-api/yarn.lock" }}
    - run:
        name: Lint
        command: yarn lint

workflows:
  version: 2
  ci:
    jobs:
    - install
    - test:
        requires:
        - install
    - lint:
        requires:
        - install
