export enum SymeoExceptionCode {
  CONFIGURATION_NOT_FOUND = 'CONFIGURATION_NOT_FOUND',
  REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
  GITHUB_FILE_CONTENT_NOT_FOUND = 'GITHUB_FILE_CONTENT_NOT_FOUND',
}
