Description: Symeo Api - Dynamo DB Table
Parameters:
  SymeoApiTableName:
    Type: String
    Default: symeo-api
  DynamoScalingRoleArn:
    Type: String
  Env:
    Type: String
    Default: dev

Resources:
  SymeoApiBoardsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub ${SymeoApiTableName}-configurations-${Env}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
      -
        AttributeName: id
        AttributeType: S
      KeySchema:
      -
        AttributeName: id
        KeyType: HASH
      Tags:
      - Key: Project
        Value: SymeoApi
      - Key: Env
        Value: !Ref Env

Outputs:
  SymeoApiBoardsTable:
    Value: !Ref SymeoApiBoardsTable
