AWSTemplateFormatVersion: '2010-09-09'

Description: Symeo Api - RDS Database

Parameters:
  Env:
    Description: The environment name deployed
    Type: String
    Default: staging

  DBUsername:
    Description: The database username
    Type: String
    Default: symeo

  DBPassword:
    Description: The database password
    Type: String

  DBName:
    Description: The database password
    Type: String
    Default: symeoapi

  SymeoApiDatabaseSg:
    Description: The database security group
    Type: String

Resources:
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub symeo-api-db-${Env}
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DatabaseName: !Ref DBName
      Engine: aurora-postgresql
      EngineMode: serverless # TODO: check if it makes more sense to have a reserved instance
      DeletionProtection: true
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 16
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      VpcSecurityGroupIds:
        - !Ref SymeoApiDatabaseSg

Outputs:
  ClusterEndpoint:
    Value: !GetAtt RDSCluster.Endpoint.Address

  DBPort:

    Value: !GetAtt RDSCluster.Endpoint.Port

  DBUsername:
    Value: !Ref DBUsername

  DBName:
    Value: !Ref DBName
